# Define the playbook name and begin the playbook
- name: Install DevOps Tools
  # Define the hosts to run the playbook on
  hosts: localhost
  # Grant sudo privileges to run tasks as a superuser
  become: yes
  # Define the tasks to be executed
  tasks:
    # Task to update the apt cache
    - name: Update apt cache
      apt:
        update_cache: yes

    # Task to install common packages
    - name: Install common packages
      apt:
        name:
          - gnupg
          - software-properties-common
          - apt-transport-https
          - ca-certificates
          - curl
          - wget
          - unzip
        state: present

    # Jenkins installation
    # Task to update all packages to their latest version
    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest

    # Task to download Jenkins key
    - name: Download Jenkins key
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        
    # Task to add Jenkins repository
    - name: Add Jenkins repo
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
        state: present
        filename: jenkins.list  

    # Task to install fontconfig package
    - name: Install fontconfig
      ansible.builtin.apt:
        name: fontconfig
        state: present

    # Task to install Java Runtime Environment
    - name: Install Java
      ansible.builtin.apt:
        name: openjdk-17-jre
        state: present

    # Task to install Jenkins
    - name: Install Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present  

    # Task to ensure Jenkins service is running and enabled
    - name: Ensure Jenkins service is running
      ansible.builtin.systemd:
        name: jenkins
        state: started
        enabled: yes 
           
    # HashiCorp (Terraform) setup
    # Task to add HashiCorp GPG key
    - name: Add HashiCorp GPG key
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /usr/share/keyrings/hashicorp-archive-keyring.asc
        mode: '0644'

    # Task to add HashiCorp repository
    - name: Add HashiCorp repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present
        filename: hashicorp
        update_cache: yes

    # Task to install Terraform
    - name: Install Terraform
      ansible.builtin.apt:
        name: terraform
        state: present
        update_cache: yes

    # Snyk installation
    # Task to download and install Snyk
    - name: Download and install Snyk
      ansible.builtin.get_url:
        url: https://static.snyk.io/cli/latest/snyk-linux
        dest: /usr/local/bin/snyk
        mode: '0755'

    # Helm installation
    # Task to download Helm installation script
    - name: Download Helm installation script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0700'

    # Task to install Helm
    - name: Install Helm
      ansible.builtin.command: /tmp/get_helm.sh

    # Kubernetes tools installation
    # Task to create a directory for Kubernetes tools
    - name: Create Kubernetes directory
      ansible.builtin.file:
        path: /usr/local/bin
        state: directory
        mode: '0755'

    # Task to download kubectl
    - name: Download kubectl
      ansible.builtin.get_url:
        url: https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    # Task to download kubeadm
    - name: Download kubeadm
      ansible.builtin.get_url:
        url: https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubeadm
        dest: /usr/local/bin/kubeadm
        mode: '0755'

    # Task to download kubelet
    - name: Download kubelet
      ansible.builtin.get_url:
        url: https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubelet
        dest: /usr/local/bin/kubelet
        mode: '0755'

    # Task to verify kubectl installation
    - name: Verify kubectl installation
      ansible.builtin.command: kubectl version --client
      register: kubectl_version
      changed_when: false

    # Task to verify kubeadm installation
    - name: Verify kubeadm installation
      ansible.builtin.command: kubeadm version
      register: kubeadm_version
      changed_when: false

    # Task to display Kubernetes tools versions
    - name: Display Kubernetes tools versions
      ansible.builtin.debug:
        var: item
      loop:
        - "{{ kubectl_version.stdout }}"
        - "{{ kubeadm_version.stdout }}"

    # Task to download kubelet service file
    - name: Download kubelet service file
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/kubernetes/release/v0.4.0/cmd/kubepkg/templates/latest/deb/kubelet/lib/systemd/system/kubelet.service
        dest: /etc/systemd/system/kubelet.service
        mode: '0644'

    # Task to create directory for kubelet service
    - name: Create kubelet service directory
      ansible.builtin.file:
        path: /etc/systemd/system/kubelet.service.d
        state: directory
        mode: '0755'

    # Task to download kubelet service configuration
    - name: Download kubelet service config
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/kubernetes/release/v0.4.0/cmd/kubepkg/templates/latest/deb/kubeadm/10-kubeadm.conf
        dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
        mode: '0644'

    # Task to enable and start kubelet service
    - name: Enable and start kubelet service
      ansible.builtin.systemd:
        name: kubelet
        state: started
        enabled: yes
        daemon_reload: yes

    # Docker installation
    # Task to add Docker GPG apt key
    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    # Task to add Docker repository
    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    # Task to update apt and install Docker packages
    - name: Update apt and install docker-ce
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    # Task to add user to Docker group
    - name: Add user to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes

    # Task to set permissions for Docker socket
    - name: Set permissions for Docker socket
      ansible.builtin.file:
        path: /var/run/docker.sock
        mode: '0777'

    # Task to restart Docker service
    - name: Restart Docker service
      ansible.builtin.systemd:
        name: docker
        state: restarted
        daemon_reload: yes        

    # AWS CLI installation
    # Task to check if AWS CLI is installed
    - name: Check if AWS CLI is installed
      ansible.builtin.command: aws --version
      register: awscli_version
      ignore_errors: yes
      changed_when: false

    # Task to download AWS CLI installer if not already installed
    - name: Download AWS CLI installer
      ansible.builtin.unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp
        remote_src: yes
      when: awscli_version.rc != 0

    # Task to install AWS CLI
    - name: Install AWS CLI
      ansible.builtin.command: /tmp/aws/install
      when: awscli_version.rc != 0

    # Task to clean up AWS CLI installer
    - name: Clean up AWS CLI installer