# Define the Kubernetes API version
apiVersion: apps/v1
# Define the type of Kubernetes object
kind: Deployment
# Define the metadata for the Deployment object
metadata:
  # Define the name of the Deployment
  name: api
  # Define the namespace where the Deployment will be created
  namespace: nepaltech
  # Define the labels for the Deployment
  labels:
    # Define the role label
    role: api
    # Define the environment label
    env: demo

# Define the specification for the Deployment
spec:
  # Define the number of replicas for the Deployment
  replicas: 2
  # Define the update strategy for the Deployment
  strategy:
    # Define the type of update strategy
    type: RollingUpdate
    # Define the rolling update strategy
    rollingUpdate:
      # Define the maximum number of pods that can be created during the update
      maxSurge: 1
      # Define the maximum number of pods that can be unavailable during the update
      maxUnavailable: 25%

  # Define the selector for the Deployment
  selector:
    # Define the match labels for the selector
    matchLabels:
      # Define the role label
      role: api

  # Define the template for the Deployment
  template:
    # Define the metadata for the template
    metadata:
      # Define the labels for the template
      labels:
        # Define the role label
        role: api

    # Define the specification for the template
    spec:
      # Define the containers for the template
      containers:
      - # Define the name of the container
        name: api
        # Define the image for the container
        image: cloudacademydevops/api:v3
        # Define the image pull policy for the container
        imagePullPolicy: Always
        # Define the environment variables for the container
        env:
          - # Define the name of the environment variable
            name: MONGO_CONN_STR
            # Define the value of the environment variable
            value: mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/langdb?replicaSet=rs0
          - # Define the name of the environment variable
            name: MONGO_USERNAME
            # Define the value of the environment variable from a secret
            valueFrom:
              secretKeyRef:
                # Define the name of the secret
                name: mongodb-secret
                # Define the key of the secret
                key: username
          - # Define the name of the environment variable
            name: MONGO_PASSWORD
            # Define the value of the environment variable from a secret
            valueFrom:
              secretKeyRef:
                # Define the name of the secret
                name: mongodb-secret
                # Define the key of the secret
                key: password

        # Define the ports for the container
        ports:
        - # Define the container port
          containerPort: 8080

        # Define the liveness probe for the container
        livenessProbe:
          # Define the HTTP GET request for the liveness probe
          httpGet:
            # Define the path of the HTTP GET request
            path: /ok
            # Define the port of the HTTP GET request
            port: 8080
          # Define the initial delay for the liveness probe
          initialDelaySeconds: 2
          # Define the period for the liveness probe
          periodSeconds: 5

        # Define the readiness probe for the container
        readinessProbe:
          # Define the HTTP GET request for the readiness probe
          httpGet:
            # Define the path of the HTTP GET request
            path: /ok
            # Define the port of the HTTP GET request
            port: 8080
          # Define the initial delay for the readiness probe
          initialDelaySeconds: 5
          # Define the period for the readiness probe
          periodSeconds: 5
          # Define the success threshold for the readiness probe
          successThreshold: 1
