# Define the Kubernetes API version
apiVersion: v1
# Define the type of Kubernetes object
kind: Service
# Define the metadata for the Service object
metadata:
  # Define the name of the Service
  name: mongo
  # Define the namespace where the Service will be created
  namespace: nepaltech
  # Define the labels for the Service
  labels:
    # Define the role label
    role: db
    # Define the environment label
    env: demo

# Define the specification for the Service
spec:
  # Define the ports for the Service
  ports:
  - # Define the port number for the Service
    port: 27017
    # Define the target port number for the Service
    targetPort: 27017
    # Note: The port and targetPort numbers are the same, which means that the Service will expose port 27017 and forward traffic to port 27017 on the selected pods.

  # Define the cluster IP for the Service
  clusterIP: None
  # Note: Setting clusterIP to None means that this Service will not be assigned a cluster IP address.
  # This is typically used for headless Services, where the Service is used to provide a network identity for a group of pods, but does not need to be accessible via a cluster IP address.

  # Define the selector for the Service
  selector:
    # Define the role label that the Service will select
    role: db
    # Note: The Service will select all pods that have the label "role: db" and forward traffic to them.
    # This allows the Service to provide a network identity for the MongoDB pods and enable communication between them.
