# Define the Kubernetes API version
apiVersion: v1
# Define the type of Kubernetes object
kind: Secret
# Define the metadata for the Secret object
metadata:
  # Define the name of the Secret
  name: mongodb-secret
  # Define the namespace where the Secret will be created
  namespace: nepaltech

# Define the data for the Secret
data:
  # Define the username for the MongoDB secret
  username: YWRtaW4=
  # Define the password for the MongoDB secret
  password: cGFzc3dvcmQ=
  # Note: These values are base64 encoded, which is a way to represent binary data as text.
  # The username and password are encoded to prevent them from being stored in plain text.
  # To decode these values, you can use a base64 decoder or the `base64 --decode` command.
  # For example, the username "YWRtaW4=" decodes to "admin" and the password "cGFzc3dvcmQ=" decodes to "password".
