apiVersion: v1 # Specifies the API version as 'v1' for the Service resource
kind: Service # Defines the kind of object as a Service
metadata:
  name: rabbitmq # Sets the name of the Service to 'rabbitmq'
  labels:
    service: rabbitmq # Adds a label 'service' with the value 'rabbitmq' to the metadata
spec:
  ports:
  - name: tcp-amqp # Names this port configuration as 'tcp-amqp'
    port: 5672 # Exposes port 5672 on the Service
    targetPort: 5672 # Redirects traffic to port 5672 on the container
  - name: http-management # Names this port configuration as 'http-management'
    port: 15672 # Exposes port 15672 on the Service
    targetPort: 15672 # Redirects traffic to port 15672 on the container
  - name: tcp-epmd # Names this port configuration as 'tcp-epmd'
    port: 4369 # Exposes port 4369 on the Service
    targetPort: 4369 # Redirects traffic to port 4369 on the container
  selector:
    service: rabbitmq # Selects pods with the label 'service: rabbitmq'
