apiVersion: v1 # Specifies the API version as 'v1' for the Service resource
kind: Service # Defines the kind of object as a Service
metadata:
  name: ratings # Sets the name of the Service to 'ratings'
  labels:
    service: ratings # Adds a label 'service' with the value 'ratings' to the metadata
spec:
  ports:
  - name: http # Names this port configuration as 'http'
    port: 80 # Exposes port 80 on the Service
    targetPort: 80 # Redirects traffic to port 80 on the container
  selector:
    service: ratings # Selects pods with the label 'service: ratings'
