apiVersion: v1 # Specifies the API version as 'v1' for the Service resource
kind: Service # Defines the kind of object as a Service
metadata:
  labels:
    service: redis # Adds a label 'service' with the value 'redis' to the metadata
  name: redis # Sets the name of the Service to 'redis'
spec:
  ports:
  - name: redis # Names this port configuration as 'redis'
    port: 6379 # Exposes port 6379 on the Service
    targetPort: 6379 # Redirects traffic to port 6379 on the container
  selector:
    service: redis # Selects pods with the label 'service: redis'
