apiVersion: v1 # Specifies the API version as 'v1' for the Service resource
kind: Service # Defines the kind of object as a Service
metadata:
  name: shipping # Sets the name of the Service to 'shipping'
  labels:
    service: shipping # Adds a label 'service' with the value 'shipping' to the metadata
spec:
  ports:
  - name: http # Names this port configuration as 'http'
    port: 8080 # Exposes port 8080 on the Service
    targetPort: 8080 # Redirects traffic to port 8080 on the container
  selector:
    service: shipping # Selects pods with the label 'service: shipping'
