apiVersion: apps/v1                         # Specifies the API version
kind: Deployment                            # Specifies the kind of resource, which is Deployment
metadata:
  name: two-tier-app                        # Name of the Deployment resource
  labels:
    app: two-tier-app                       # Labels to categorize the resource
spec:
  replicas: 1                               # Number of pod replicas to maintain
  selector:
    matchLabels:
      app: two-tier-app                     # Labels used to select the pods managed by this Deployment
  template:
    metadata:
      labels:
        app: two-tier-app                   # Labels applied to the pods created by this template
    spec:
      containers:
        - name: two-tier-app                # Name of the container
          image: lmen776/EKS-2-TIER-FLASK-APP:tag # Updated Docker image to use for the container
          env:
            - name: MYSQL_HOST
              value: "10.98.19.211"         # Environment variable for MySQL host; this is your MySQL's service cluster IP, make sure to change it with yours
            - name: MYSQL_PASSWORD
              value: "admin"                # Environment variable for MySQL password
            - name: MYSQL_USER
              value: "admin"                # Environment variable for MySQL user
            - name: MYSQL_DB
              value: "mydb"                 # Environment variable for MySQL database name
          ports:
            - containerPort: 5000           # Port on which the container will accept connections
          imagePullPolicy: Always           # Specifies the image pull policy, which is Always to always pull the latest image
