apiVersion: v1                             # Specifies the API version
kind: Service                              # Specifies the kind of resource, which is Service
metadata:
  name: two-tier-app-service               # Name of the Service resource
spec:
  selector:
    app: two-tier-app                      # Labels used to select the pods targeted by this Service
  ports:
    - protocol: TCP                        # Protocol used by the Service, which is TCP
      port: 80                             # Port on which the Service will be accessible
      targetPort: 5000                     # Port on the container to which traffic will be directed
      nodePort: 30004                      # Port on the node which maps to the Service port
  type: NodePort                           # Specifies the type of Service, which is NodePort to expose the Service on a static port on each node
