# Use an official Python runtime as the base image
FROM python:3.9-slim # The base image is the official slim version of Python 3.9

# Set the working directory in the container
WORKDIR /app # Sets the working directory to /app in the container

# Install required packages for system
RUN apt-get update -y \ # Update the package list
    && apt-get upgrade -y \ # Upgrade all installed packages to their latest versions
    && apt-get install -y gcc default-libmysqlclient-dev pkg-config \ # Install the necessary packages: gcc, default-libmysqlclient-dev, pkg-config
    && rm -rf /var/lib/apt/lists/* # Clean up the package lists to reduce the image size

# Copy the requirements file into the container
COPY requirements.txt . # Copy the requirements.txt file from the host to the current directory in the container

# Install app dependencies
RUN pip install mysqlclient # Install the mysqlclient package
RUN pip install -r requirements.txt # Install the packages listed in the requirements.txt file

# Copy the rest of the application code
COPY . . # Copy the rest of the application code from the host to the current directory in the container

# Specify the command to run your application
CMD ["python", "app.py"] # The command to run the application: execute the app.py file with Python
