version: '3' # Version of the Docker Compose file format

services:
  
  backend:
    image: lmen776/EKS-2-TIER-FLASK-APP:tag # Use the specified version of your custom Docker image
    ports:
      - "5000:5000" # Map port 5000 of the host to port 5000 of the container
    environment:
      MYSQL_HOST: mysql # Set the MySQL host environment variable to 'mysql', referring to the mysql service
      MYSQL_USER: admin # Set the MySQL user environment variable to 'admin'
      MYSQL_PASSWORD: admin # Set the MySQL password environment variable to 'admin'
      MYSQL_DB: myDb # Set the MySQL database name environment variable to 'myDb'
    depends_on:
      - mysql # Ensure the backend service waits for the mysql service to start before running

  mysql:
    image: mysql:5.7 # Use the MySQL version 5.7 image
    ports:
      - "3306:3306" # Map port 3306 of the host to port 3306 of the container
    environment:
      MYSQL_ROOT_PASSWORD: admin # Set the root password for MySQL
      MYSQL_DATABASE: myDb # Create a MySQL database named 'myDb'
      MYSQL_USER: admin # Create a MySQL user named 'admin'
      MYSQL_PASSWORD: admin # Set the password for the MySQL user 'admin'
    volumes:
      - ./message.sql:/docker-entrypoint-initdb.d/message.sql # Mount the SQL script into the container's /docker-entrypoint-initdb.d directory to automatically create the table
      - mysql-data:/var/lib/mysql # Mount the volume for MySQL data storage

volumes:
  mysql-data: # Define a named volume for MySQL data persistence
